services:
  pgdatabase_hwkA:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=trip_data
    volumes:
      - ./trip_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
  
  pgadmin_hwkA:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
    
